language: node_js
node_js:
  - "12"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: examples
  on:
    branch: master
script:
  - npm test